get:
  tags:
    - CPU/GPU Miner
  summary: Get a list of playbook for a given CPU/GPU miner
  description: "This endpoint helps submitting cpu/gpu mining rig - monitor data. This api should be call every minute"
  operationId: get-cpu-gpu-miner-playbook-list
  security:
    - api_code: []
  responses:
    '200':
      description: "CPU/GPU miner playbook list"
      content:
        application/json:
          schema:
            $ref: ../components/schemas/CPU_GPU_MINER_PLAYBOOK.yaml

    '401':
      description: Invalid API_CODE
      content:
        application/json:
          schema:
            $ref: ../components/schemas/401_Unauthorized.yaml
