openapi: 3.1.0
info:
  version: 2.0.0
  title: Mining Rig Monitor

  contact:
    name: Contact our support
    email: nguyenvinhlinh93@gmail.com
  license:
    name: GNU GENERAL PUBLIC LICENSE Version 3
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
    altText: OpenAPI example logo
  description: >
    This is an API for Mining Rig Monitor Software.

tags:
  - name: Ping Pong
    description: "Ping Pong"
  - name: ASIC Miner
    description: "ASIC Miner API"
  - name: CPU/GPU Miner
    description: "CPU/GPU Miner API"

servers:
  - url: http://127.0.0.1:4000/api/v1
  - url: https://mining_rig_monitor_dev.hexalink.xyz/api/v1
  - url: https://mining_rig_monitor_staging.hexalink.xyz/api/v1
  - url: https://mining_rig_monitor.hexalink.xyz/api/v1
paths:
  '/ping':
    $ref: 'paths/ping.yaml'

  '/asic_miners/specs':
    $ref: 'paths/asic_specs.yaml'

  '/asic_miners/logs':
    $ref: 'paths/asic_monitor_data.yaml'

  '/cpu_gpu_miners/specs':
    $ref: 'paths/cpu_gpu_miner_specs.yaml'

  '/cpu_gpu_miners/logs':
    $ref: 'paths/cpu_gpu_miner_logs.yaml'

  '/cpu_gpu_miners/playbooks':
    $ref: './paths/cpu_gpu_miner_playbooks.yaml'

  '/cpu_gpu_miners/playbooks/{playbook_id}/module':
    $ref: './paths/cpu_gpu_miner_playbook_module.yaml'

components:
  securitySchemes:
    api_code:
      description: "It's a must to assign request header named `API_CODE`"
      type: apiKey
      in: header
      name: API_CODE
